### ISSUE TITLE
Add core GitHub commands

### ISSUE THREAD

**Issue by pcgeek86** [pcgeek86/PSGitHub#1]
We need to fill out some of the core commands for interacting with GitHub.
# Core
- [ ] We need to figure out how to handle data pagination
# Authentication
- [ ] Support authentication in Microsoft Azure Automation runbook service, using PSCredential asset type
- [x] Encrypt GitHub Personal Access Token on-disk in JSON configuration file
- [ ] Add support for multiple usernames and Personal Access Tokens
  - Enable user to switch between contexts
  - Enable user to specify a GitHub profile during each command call
# Repositories

https://developer.github.com/v3/repos
- [ ] List the authenticated user's GitHub repositories
- [ ] List a specific user's public GitHub repositories
- [ ] List all public repositories
- [x] Create new repositories
- [ ] Edit / modify properties of existing repositories
- [x] Delete existing repositories
- [ ] List contributors
- [ ] List languages in project
- [ ] List branches
- [ ] Get a specific branch
- [ ] List Git tags on a specific repository
# Pull Requests

https://developer.github.com/v3/pulls/
- [ ] View outstanding Pull Requests for an owner / repository
- [ ] Merge one or more Pull Requests (one PowerShell command)
- [ ] Update a Pull Request (title, description, state)
- [ ] Create a Pull Request
# Search

https://developer.github.com/v3/search/
- [x] Search for GitHub repositories
- [ ] Search for GitHub issues
- [ ] Search for GitHub users
- [ ] Search for code
# Issues

https://developer.github.com/v3/issues/
- [x] Create new GitHub issues
- [ ] Close or re-open GitHub issues
- [ ] List all or individual issues
- [ ] Lock and unlock issues
# Milestones

https://developer.github.com/v3/issues/milestones/
- [ ] Create a milestone
- [ ] List all milestones
- [ ] Get a specific milestone
- [ ] Update a milestone
- [ ] Delete a milestone

**Comment by exactmike** [comment]
Pull request I posted today addresses:  
- List the authenticated user's GitHub repositories
- List a specific user's public GitHub repositories
I think with a little more effort and another parameterset we could also address 
- List all public repositories
